platform: x64
configuration: Release
image: Visual Studio 2019
install:
 - cmd: choco install swig -y --version 3.0.12 & exit 0
build_script:
 - cmake -P ci-build.cmake
 - cmake --build build --config Release --target INSTALL
test_script:
 - set PATH=%PATH%;build\gtest\lib
 - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019 Preview" build\bin\release\Test_Ogre.exe --gtest_filter=-MeshWithoutIndexDataTests*
cache:
- ogredeps -> CMake/Dependencies.cmake
artifacts:
  - path: build/sdk
    name: ogre-sdk-master1-vc16-x64
