name: PIP packages
on:
  push:
    branches: [pip]

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Remove Perl Strawberry (Workaround)
        run: rm -rf C:/Strawberry/
        shell: bash

      - name: Install Dependencies
        run: choco install swig ninja -y # need swig 4+ for python 3.8

      - name: Build
        run: |
          pip install setuptools wheel twine
          pip wheel . --verbose

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: wheel-win
          path: "*.whl"
